"""Top-level orchestrator for the agentic investigation layer (M10 Stage 1):
gather -> map to the existing response playbooks -> optionally narrate -> persist.

Aegis only *recommends* here — nothing in this module (or anything it calls) quarantines an
email, resets a credential, blocks a sender, or notifies anyone automatically. Recommended
steps are the same PlaybookStep shape app.api.routes.remediation already serves, generated by
the SAME deterministic engine (app.remediation.playbook/intrusion_playbook); a human still
approves/marks each one done exactly as before. Nothing about this feature changes that
contract.
"""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

from sqlalchemy.orm import Session

from app.core.config import settings
from app.db.models import Case, Incident, Investigation
from app.investigation.gather import InvestigationContext, gather_context
from app.investigation.llm_summary import generate_investigation_summary
from app.remediation.intrusion_playbook import generate_intrusion_playbook
from app.remediation.playbook import PlaybookStep, generate_playbook


def _control_refs_for_step(framework_mappings: dict, related_ids: list[str]) -> list[dict]:
    """Mirrors app.api.routes.remediation._control_refs_for_step exactly, returning plain
    dicts (not the route layer's Pydantic model) since this is persisted as JSON — the API
    layer re-wraps these into RemediationControlRef when serving a response. Duplicated
    rather than imported from the route module on purpose: domain/orchestration logic
    (this package) shouldn't depend on the API route layer."""
    seen: set[tuple[str, str]] = set()
    refs: list[dict] = []
    for framework_key, control_refs in framework_mappings.items():
        for ref in control_refs:
            if ref["indicator_id"] not in related_ids:
                continue
            key = (framework_key, ref["control_id"])
            if key in seen:
                continue
            seen.add(key)
            refs.append(
                {
                    "framework_key": framework_key,
                    "control_id": ref["control_id"],
                    "control_name": ref["control_name"],
                }
            )
    return refs


def _steps_to_dicts(steps: list[PlaybookStep], framework_mappings: dict) -> list[dict]:
    return [
        {
            "step_id": step.step_id,
            "title": step.title,
            "description": step.description,
            "category": step.category,
            "related_indicator_ids": step.related_indicator_ids,
            "control_refs": _control_refs_for_step(framework_mappings, step.related_indicator_ids),
        }
        for step in steps
    ]


def _recommended_steps(case: Case | None, incident: Incident | None) -> list[dict]:
    if case is not None:
        indicator_ids = [i["id"] for i in case.indicators]
        return _steps_to_dicts(generate_playbook(indicator_ids), case.framework_mappings)
    assert incident is not None
    finding_ids = [f["id"] for f in incident.findings]
    return _steps_to_dicts(generate_intrusion_playbook(finding_ids), incident.framework_mappings)


def _context_to_dicts(context: InvestigationContext) -> dict:
    return {
        "sender_intelligence": context.sender.to_dict() if context.sender else {},
        "related_cases": [rc.to_dict() for rc in context.related_cases],
        "related_incidents": [ri.to_dict() for ri in context.related_incidents],
        "threat_intel_hits": context.threat_intel_hits,
        "threat_level": context.threat_level.to_dict() if context.threat_level else None,
        "ueba_findings": context.ueba_findings,
        "timeline": [entry.to_dict() for entry in context.timeline],
        "scope": context.scope,
    }


def save_investigation(
    db: Session,
    account_id: UUID,
    *,
    case: Case | None = None,
    incident: Incident | None = None,
    trigger: str,
    now: datetime | None = None,
) -> Investigation:
    """Gathers context, generates recommendations, optionally narrates, and upserts the
    Investigation row for this case/incident (replacing any prior one — see
    app.db.models.Investigation's docstring for why this is upsert, not append-only). Does
    NOT commit; callers commit alongside the rest of their transaction, same convention as
    app.early_warning.hooks.evaluate_actors / app.threat_level.hooks.

    Exactly one of case/incident must be given. Never raises for an LLM failure — a failed
    or disabled narrative simply leaves summary fields None while every deterministic field
    is still populated (see app.investigation.llm_summary's module docstring)."""
    if (case is None) == (incident is None):
        raise ValueError("save_investigation requires exactly one of case or incident")
    if now is None:
        now = datetime.now(timezone.utc)

    context = gather_context(db, account_id, case=case, incident=incident, now=now)
    recommended_steps = _recommended_steps(case, incident)

    summary = summary_model = summary_evidence_strength = None
    if settings.enable_llm_reasoning:
        result = generate_investigation_summary(context)
        if result is not None:
            summary = result.narrative
            summary_model = result.model
            summary_evidence_strength = result.evidence_strength

    context_fields = _context_to_dicts(context)

    # The "exactly one of case/incident" guard above means exactly one of these two filters
    # is a real UUID match and the other is an `IS NULL` — never both None, so this can never
    # accidentally match an unrelated row of the other parent type.
    existing = (
        db.query(Investigation)
        .filter(
            Investigation.account_id == account_id,
            Investigation.case_id == (case.id if case is not None else None),
            Investigation.incident_id == (incident.id if incident is not None else None),
        )
        .first()
    )

    if existing is not None:
        existing.updated_at = now
        existing.trigger = trigger
        existing.actor = context.actor
        existing.verdict = context.verdict
        existing.score = context.score
        existing.sender_intelligence = context_fields["sender_intelligence"]
        existing.related_cases = context_fields["related_cases"]
        existing.related_incidents = context_fields["related_incidents"]
        existing.threat_intel_hits = context_fields["threat_intel_hits"]
        existing.threat_level = context_fields["threat_level"]
        existing.ueba_findings = context_fields["ueba_findings"]
        existing.timeline = context_fields["timeline"]
        existing.scope = context_fields["scope"]
        existing.recommended_steps = recommended_steps
        existing.summary = summary
        existing.summary_model = summary_model
        existing.summary_evidence_strength = summary_evidence_strength
        return existing

    investigation = Investigation(
        account_id=account_id,
        case_id=case.id if case is not None else None,
        incident_id=incident.id if incident is not None else None,
        created_at=now,
        updated_at=now,
        trigger=trigger,
        actor=context.actor,
        verdict=context.verdict,
        score=context.score,
        recommended_steps=recommended_steps,
        summary=summary,
        summary_model=summary_model,
        summary_evidence_strength=summary_evidence_strength,
        **context_fields,
    )
    db.add(investigation)
    return investigation


def maybe_auto_investigate(
    db: Session,
    account_id: UUID,
    *,
    case: Case | None = None,
    incident: Incident | None = None,
    now: datetime | None = None,
) -> Investigation | None:
    """Called right after a Case/Incident is persisted. Fires only when the verdict is in
    settings.investigation_auto_trigger_verdicts (suspicious/malicious by default) — a safe
    email never gets an investigation. Swallows any exception: investigation generation must
    never break email analysis or event ingestion, the same graceful-degradation discipline
    as every LLM-touching path in this codebase. Returns None on skip OR failure; callers
    that want the result should re-fetch rather than branch on this return value."""
    verdict = case.verdict if case is not None else incident.verdict  # type: ignore[union-attr]
    if verdict not in settings.investigation_auto_trigger_verdicts:
        return None
    try:
        return save_investigation(db, account_id, case=case, incident=incident, trigger="auto", now=now)
    except Exception:  # noqa: BLE001 - never let investigation generation break the caller's flow.
        return None
