#!/usr/bin/env python3
"""Downloads and normalizes threat-intelligence feeds into the committed static snapshots
backend/app/threat_intel/data/{hostnames,urls,ips}.txt (consumed by app.threat_intel.loader)
and regenerates backend/app/threat_intel/data/sources.md.

Run this manually, locally, whenever you want to refresh the bundled data — NOT part of any
deploy/build/CI step (same convention the retired scripts/extract_phishtank_hosts.py
followed). The snapshots go stale the moment infrastructure churns after the fetch date; a
match is corroborating evidence, not a live reputation check — see
app/threat_intel/loader.py's module docstring.

Feeds, and why only these two (see the Stage 1 plan's license research before adding more):
  - Tor Project exit-node list (https://check.torproject.org/torbulkexitlist) — CC0, the
    Tor Project's own no-copyright dedication on Tor Metrics data. Individual IPs, one per
    line, no registration required.
  - PhishTank (https://data.phishtank.com/data/online-valid.csv) — phishtank.org's Terms of
    Use state API data is "available for commercial use without charge" (there's a CC BY-SA
    2.5 notice on the same page — attribute-and-share-alike for the compiled data, recorded
    verbatim in sources.md; this isn't a substitute for your own legal review). Same
    unauthenticated bulk URL ml/aegis_ml/download/phishtank.py already uses, reimplemented
    standalone here so this script has no dependency on the ml/ package.

URLhaus, Feodo Tracker, OpenPhish, and a Spamhaus-sourced abused-TLD list were investigated
and DROPPED — abuse.ch's fair-use tier and OpenPhish's ToS both explicitly exclude
commercial/product use without a paid subscription or written consent, and Spamhaus's DROP
Fair Use Policy bars commercial use of the list content, with no other clean, clearly-licensed
free "TLD abuse" source found. Do not add them back without a paid license or written
permission — the architecture (app.threat_intel.loader) supports more feeds whenever one
becomes available; this script just doesn't fetch any today.

Usage: python3 scripts/refresh_threat_intel.py
"""

from __future__ import annotations

import csv
import io
import urllib.request
from datetime import date
from pathlib import Path
from urllib.parse import urlsplit

REPO_ROOT = Path(__file__).parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw" / "threat_intel"
DATA_DIR = REPO_ROOT / "backend" / "app" / "threat_intel" / "data"

TOR_EXIT_LIST_URL = "https://check.torproject.org/torbulkexitlist"
PHISHTANK_CSV_URL = "https://data.phishtank.com/data/online-valid.csv"
USER_AGENT = "cordon-threat-intel-refresh/0.1 (defensive-security; contact via GitHub)"


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def _fetch_tor_exit_nodes() -> set[str]:
    raw = _fetch(TOR_EXIT_LIST_URL)
    (RAW_DIR / "tor_exit_nodes.txt").write_bytes(raw)
    ips = {line.strip() for line in raw.decode("utf-8", errors="replace").splitlines() if line.strip()}
    return ips


def _fetch_phishtank() -> tuple[set[str], set[str]]:
    raw = _fetch(PHISHTANK_CSV_URL)
    (RAW_DIR / "phishtank_online-valid.csv").write_bytes(raw)

    hosts: set[str] = set()
    urls: set[str] = set()
    reader = csv.DictReader(io.StringIO(raw.decode("utf-8", errors="replace")))
    for row in reader:
        url = (row.get("url") or "").strip()
        if not url:
            continue
        try:
            netloc = urlsplit(url).netloc
        except ValueError:
            continue
        netloc = netloc.rsplit("@", 1)[-1].split(":", 1)[0].lower()
        if netloc:
            hosts.add(netloc)
        urls.add(url.lower())
    return hosts, urls


def _write_snapshot(path: Path, snapshot_date: str, entries: dict[str, str]) -> None:
    lines = [f"# snapshot_date: {snapshot_date}"]
    lines.extend(f"{feed}\t{value}" for value, feed in sorted(entries.items()))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_sources_md(snapshot_date: str, counts: dict[str, int], tor_fetch_failed: bool) -> None:
    tor_status = (
        "- **This run's fetch FAILED** (see the script's console output) — ips.txt's "
        "tor_exit_node entries are whatever a PRIOR successful run left, not refreshed "
        "today. Re-run this script from a network that can reach check.torproject.org.\n"
        if tor_fetch_failed
        else ""
    )
    content = f"""# Threat-intel feed sources

Regenerated by `scripts/refresh_threat_intel.py` — snapshot date **{snapshot_date}**.

## Tor Project exit-node list

- Source: <{TOR_EXIT_LIST_URL}>
- License: **CC0** — Tor Metrics data carries a no-copyright (CC0) dedication; the Tor
  Project has waived all copyright and related/neighboring rights.
{tor_status}- Entries this snapshot: {counts.get("tor_exit_node", 0)}
- Artifact type: IPs (ips.txt, feed id `tor_exit_node`)

## PhishTank

- Source: <{PHISHTANK_CSV_URL}>
- License: phishtank.org's Terms of Use state API data is **"available for commercial use
  without charge."** The same terms page carries a CC BY-SA 2.5 notice — attribute and
  share-alike for redistributions of the compiled data (this file is that attribution).
  Not a substitute for your own legal review.
- Entries this snapshot: {counts.get("phishtank_hosts", 0)} hostnames,
  {counts.get("phishtank_urls", 0)} URLs
- Artifact type: hostnames + URLs (hostnames.txt / urls.txt, feed id `phishtank`)

## Feeds investigated and NOT used (license-restricted for commercial-product embedding)

- **abuse.ch (URLhaus, Feodo Tracker)** — fair-use free tier explicitly excludes
  "companies... with commercial or for-profit needs"; requires their paid commercial API.
- **OpenPhish** (free/community feed) — ToS explicitly bars use for "security operations,
  threat intelligence, detection, enrichment, product development" without written consent,
  and bars redistribution outright.
- **Spamhaus** (considered for an abused-TLD list) — DROP Fair Use Policy bars
  commercial/product use of the list content. No other clean, clearly-licensed free
  "TLD abuse" source was found.

Do not add these back without a paid license or written permission from the provider.
"""
    (DATA_DIR / "sources.md").write_text(content, encoding="utf-8")


def main() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    snapshot_date = date.today().isoformat()

    # Each feed fetched independently — a transient outage/network block on one (e.g. a
    # sandboxed CI runner without egress to a given host) shouldn't prevent refreshing the
    # other. Fetch failures are reported clearly, not silently swallowed.
    tor_ips: set[str] = set()
    tor_fetch_failed = False
    print(f"Fetching Tor exit-node list from {TOR_EXIT_LIST_URL} ...")
    try:
        tor_ips = _fetch_tor_exit_nodes()
        print(f"  {len(tor_ips)} exit-node IPs")
    except Exception as exc:  # noqa: BLE001 - report and continue with the other feed
        tor_fetch_failed = True
        print(f"  FAILED: {exc}\n  (leaving ips.txt's tor_exit_node entries unchanged)")

    phishtank_hosts: set[str] = set()
    phishtank_urls: set[str] = set()
    phishtank_fetch_failed = False
    print(f"Fetching PhishTank feed from {PHISHTANK_CSV_URL} ...")
    try:
        phishtank_hosts, phishtank_urls = _fetch_phishtank()
        print(f"  {len(phishtank_hosts)} hostnames, {len(phishtank_urls)} URLs")
    except Exception as exc:  # noqa: BLE001
        phishtank_fetch_failed = True
        print(f"  FAILED: {exc}\n  (leaving hostnames.txt/urls.txt's phishtank entries unchanged)")

    if tor_fetch_failed and phishtank_fetch_failed:
        raise SystemExit("Both feeds failed — nothing to write. See errors above.")

    # Only overwrite a file whose feed actually fetched successfully this run — a failed
    # fetch leaves that file exactly as it was (never wipes it to empty), consistent with
    # "leaving ... entries unchanged" above.
    if not tor_fetch_failed:
        _write_snapshot(DATA_DIR / "ips.txt", snapshot_date, {ip: "tor_exit_node" for ip in tor_ips})
    if not phishtank_fetch_failed:
        _write_snapshot(DATA_DIR / "hostnames.txt", snapshot_date, {h: "phishtank" for h in phishtank_hosts})
        _write_snapshot(DATA_DIR / "urls.txt", snapshot_date, {u: "phishtank" for u in phishtank_urls})
    _write_sources_md(
        snapshot_date,
        {
            "tor_exit_node": len(tor_ips),
            "phishtank_hosts": len(phishtank_hosts),
            "phishtank_urls": len(phishtank_urls),
        },
        tor_fetch_failed=tor_fetch_failed,
    )

    print(f"\nWrote snapshots dated {snapshot_date} to {DATA_DIR}")


if __name__ == "__main__":
    main()
